name: add-ttt-we-new-version
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  add-ttt-du-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get NewVarsion Data
        id: ReleaseData
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: ReinaS-64892/TTT-WorldExtension
          tag: ${{ github.event.inputs.tag }}
      - name: Get ZipURL
        id: ZipURL
        uses: actions/github-script@v7
        env:
          InputStr: ${{ steps.ReleaseData.outputs.assets }}
        with:
          script: |
            const {InputStr } = process.env

            for (const asset of JSON.parse(InputStr))
            {
              if (asset.name.startsWith("net.rs64.ttt-world-extension-"))
              {
                return asset.browser_download_url;
              }
            }

      - name: GetPackegeDotJsonURL
        id: PackageDotJsonURL
        uses: actions/github-script@v7
        env:
          InputStr: ${{ steps.ReleaseData.outputs.assets }}
        with:
          script: |
            const { InputStr } = process.env

            for (const asset of JSON.parse(InputStr))
            {
              if (asset.name === "package.json")
              {
                return asset.browser_download_url;
              }
            }

      - name: GetToVar
        id: PackageDotJson
        run: |
          Temp=`wget -q -O - ${{ steps.PackageDotJsonURL.outputs.result }}`
          echo 'result=' $Temp >> "$GITHUB_OUTPUT"

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: ./VpmRepo

      - name: MoveToVar
        id: VPMDotJson
        run: |
          Temp=`cat ./VpmRepo/vpm.json`
          echo 'result=' $Temp >> "$GITHUB_OUTPUT"

      - name: Debug
        run: |
          echo ${{ steps.ZipURL.outputs.result }}
          echo ${{ steps.PackageDotJson.outputs.result }}

      - name: EditURLForPackageDotJson
        id: RepoAddJsonStr
        uses: actions/github-script@v7
        env:
          InputStr: ${{ steps.PackageDotJson.outputs.result }}
          ReplaseURL: ${{ steps.ZipURL.outputs.result }}
        with:
          result-encoding: string
          script: |
            const { InputStr , ReplaseURL } = process.env

            let jsonObj = JSON.parse(InputStr);
            jsonObj.url = ReplaseURL.substring(1, ReplaseURL.length - 1);
            return JSON.stringify(jsonObj);

      - name: AddVPMDotJson
        id: AddedVPMDotJson
        uses: actions/github-script@v7
        env:
          InputStr: ${{ steps.VPMDotJson.outputs.result }}
          AddVersion: ${{ steps.RepoAddJsonStr.outputs.result }}
        with:
          script: |
            const { InputStr , AddVersion } = process.env

            let jsonObj = JSON.parse(InputStr);
            let addJsonObj = JSON.parse(AddVersion);

            jsonObj.packages[addJsonObj.name].versions[addJsonObj.version] = addJsonObj;

            return JSON.stringify(jsonObj);

      - name: Write Json
        run: |
          rm  ./VpmRepo/vpm.json
          echo ${{ steps.AddedVPMDotJson.outputs.result }} >> ./VpmRepo/vpm.json

      - name: git commit
        run: |
          cd ./VpmRepo
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./vpm.json
          git commit -m "Add TTT-WorldExtension New Version ${{ github.event.inputs.tag }}!!"
          git push origin
         